"""
🎓 ADK COURSE — "NL2SQL" Agent (Natural Language to SQL)
========================================================

This agent converts a natural language question into a SQL query,
executes it on the SQLite database, and interprets the results.

It can also progressively BUILD a feature database:
  - Create an empty feature table
  - Add columns
  - Populate with SQL query results
  - Query the feature table
  - Export to CSV

💡 PEDAGOGICAL CONTRAST with the Sales Analyst agent:

  Sales Analyst (Toolbox)         │  NL2SQL (this agent)
  ────────────────────────────────┼──────────────────────────────
  Pre-defined SQL queries         │  SQL generated by the LLM
  Agent does NOT see the schema   │  Agent KNOWS the schema
  No injection risk               │  ⚠️ Risk if used in prod
  Limited to declared tools       │  Can answer ANYTHING
  Ideal for production            │  Ideal for exploration

Architecture:

  ┌──────────────────────────────────────────┐
  │  ADK Agent (Gemini)                      │
  │                                          │
  │  tools:                                  │
  │   ├─ execute_sql()          read-only    │
  │   ├─ create_feature_table() DDL          │
  │   ├─ add_column()           DDL          │
  │   ├─ insert_query_results() DML          │
  │   ├─ list_feature_tables()  inspect      │
  │   ├─ query_feature_table()  read feat.   │
  │   └─ export_table_csv()     export       │
  └────────┬────────────────────┬─────────────┘
           │ shop.db (read)     │ features_*.db (read/write)
  ┌────────▼────────┐ ┌────────▼──────────────┐
  │  shop.db        │ │  features_<name>.db   │
  └─────────────────┘ └───────────────────────┘
"""

import csv
import io
import os
import re
import sqlite3

from google.adk.agents import Agent
from db_context import PRODUCTS_LIST, STATS_SUMMARY, TODAY

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "shop.db")
FEATURES_DIR = os.path.join(os.path.dirname(__file__), "..", "features")
os.makedirs(FEATURES_DIR, exist_ok=True)

_SAFE_NAME_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")


def _features_db_path(table_name: str) -> str:
    return os.path.join(FEATURES_DIR, f"{table_name}.db")


# ═══════════════════════════════════════════════════════════════════════
# TOOL 1 : Execute a SELECT query on shop.db (read-only)
# ═══════════════════════════════════════════════════════════════════════

def execute_sql(query: str) -> dict:
    """Execute a SQL SELECT query on the e-commerce SQLite database
    and return the results.

    IMPORTANT: use ONLY SELECT queries (read-only).
    Never use INSERT, UPDATE, DELETE, DROP or ALTER.

    Args:
        query: The SQL SELECT query to execute.

    Returns:
        A dict with columns, result rows, and row count.
    """
    try:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute(query)
        rows = cursor.fetchall()
        columns = [desc[0] for desc in cursor.description] if cursor.description else []
        results = [dict(row) for row in rows]
        conn.close()
        return {
            "status": "success",
            "sql_executed": query,
            "columns": columns,
            "row_count": len(results),
            "results": results[:50],
        }
    except Exception as e:
        return {
            "status": "error",
            "sql_executed": query,
            "error": str(e),
        }


# ═══════════════════════════════════════════════════════════════════════
# TOOL 2 : Create a feature table
# ═══════════════════════════════════════════════════════════════════════

def create_feature_table(table_name: str, columns: str) -> dict:
    """Create a new feature table in a dedicated SQLite database.

    The table is stored in a separate file (features/<table_name>.db)
    so that shop.db is never modified.

    Args:
        table_name: Table name (letters, digits, underscores only).
                    Examples: "monthly_features", "client_rfm", "product_stats"
        columns: SQL column definitions, comma-separated.
                 Examples: "month TEXT, revenue REAL, order_count INTEGER"
                           "customer TEXT PRIMARY KEY, recency INTEGER, frequency INTEGER, amount REAL"

    Returns:
        A dict with the status and path of the created database.
    """
    if not _SAFE_NAME_RE.match(table_name):
        return {"status": "error", "error": f"Invalid table name: '{table_name}'. Use only letters, digits and underscores."}
    try:
        db_path = _features_db_path(table_name)
        conn = sqlite3.connect(db_path)
        conn.execute(f"CREATE TABLE IF NOT EXISTS {table_name} ({columns})")
        conn.commit()
        col_info = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
        conn.close()
        col_list = [f"{r[1]} ({r[2]})" for r in col_info]
        return {
            "status": "success",
            "table_name": table_name,
            "db_path": db_path,
            "columns": col_list,
            "message": f"Table '{table_name}' created with {len(col_list)} columns.",
        }
    except Exception as e:
        return {"status": "error", "error": str(e)}


# ═══════════════════════════════════════════════════════════════════════
# TOOL 3 : Add a column to an existing feature table
# ═══════════════════════════════════════════════════════════════════════

def add_column(table_name: str, column_name: str, column_type: str = "REAL") -> dict:
    """Add a column to an existing feature table.

    Args:
        table_name: Name of the existing feature table.
        column_name: Name of the new column (letters, digits, underscores).
        column_type: SQLite column type (TEXT, REAL, INTEGER). Defaults to REAL.

    Returns:
        A dict with the status and the updated column list.
    """
    if not _SAFE_NAME_RE.match(table_name):
        return {"status": "error", "error": f"Invalid table name: '{table_name}'"}
    if not _SAFE_NAME_RE.match(column_name):
        return {"status": "error", "error": f"Invalid column name: '{column_name}'"}
    db_path = _features_db_path(table_name)
    if not os.path.exists(db_path):
        return {"status": "error", "error": f"Table '{table_name}' does not exist. Create it first with create_feature_table."}
    try:
        conn = sqlite3.connect(db_path)
        conn.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_type}")
        conn.commit()
        col_info = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
        conn.close()
        col_list = [f"{r[1]} ({r[2]})" for r in col_info]
        return {
            "status": "success",
            "table_name": table_name,
            "added_column": f"{column_name} ({column_type})",
            "columns": col_list,
        }
    except Exception as e:
        return {"status": "error", "error": str(e)}


# ═══════════════════════════════════════════════════════════════════════
# TOOL 4 : Populate a feature table with SELECT results
# ═══════════════════════════════════════════════════════════════════════

def insert_query_results(table_name: str, source_query: str) -> dict:
    """Execute a SELECT query on shop.db and insert the results
    into the specified feature table.

    The SELECT must return columns that match (same number and order)
    the columns of the target feature table. Uses INSERT OR REPLACE
    to overwrite existing rows if the table has a PRIMARY KEY.

    Args:
        table_name: Name of the target feature table.
        source_query: SELECT query to execute on shop.db. The returned
                      columns must match the target table columns.

    Returns:
        A dict with the number of inserted rows and a preview.
    """
    if not _SAFE_NAME_RE.match(table_name):
        return {"status": "error", "error": f"Invalid table name: '{table_name}'"}
    db_path = _features_db_path(table_name)
    if not os.path.exists(db_path):
        return {"status": "error", "error": f"Table '{table_name}' does not exist."}
    try:
        shop_conn = sqlite3.connect(DB_PATH)
        shop_conn.row_factory = sqlite3.Row
        rows = shop_conn.execute(source_query).fetchall()
        if not rows:
            shop_conn.close()
            return {"status": "success", "rows_inserted": 0, "message": "The query returned no results."}
        columns = rows[0].keys()
        shop_conn.close()

        feat_conn = sqlite3.connect(db_path)
        placeholders = ", ".join(["?"] * len(columns))
        col_names = ", ".join(columns)
        feat_conn.executemany(
            f"INSERT OR REPLACE INTO {table_name} ({col_names}) VALUES ({placeholders})",
            [tuple(row) for row in rows],
        )
        feat_conn.commit()
        count = feat_conn.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
        preview = feat_conn.execute(f"SELECT * FROM {table_name} LIMIT 5").fetchall()
        feat_conn.close()

        return {
            "status": "success",
            "rows_inserted": len(rows),
            "total_rows": count,
            "columns": list(columns),
            "preview": [dict(zip(columns, r)) for r in preview],
        }
    except Exception as e:
        return {"status": "error", "error": str(e)}


# ═══════════════════════════════════════════════════════════════════════
# TOOL 5 : List existing feature tables
# ═══════════════════════════════════════════════════════════════════════

def list_feature_tables() -> dict:
    """List all existing feature tables with their columns and row counts.

    Returns:
        A dict with the list of tables and their metadata.
    """
    tables = []
    for f in sorted(os.listdir(FEATURES_DIR)):
        if not f.endswith(".db"):
            continue
        tname = f[:-3]
        db_path = os.path.join(FEATURES_DIR, f)
        try:
            conn = sqlite3.connect(db_path)
            col_info = conn.execute(f"PRAGMA table_info({tname})").fetchall()
            count = conn.execute(f"SELECT COUNT(*) FROM {tname}").fetchone()[0]
            conn.close()
            tables.append({
                "table_name": tname,
                "columns": [f"{r[1]} ({r[2]})" for r in col_info],
                "row_count": count,
                "db_file": f,
            })
        except Exception:
            tables.append({"table_name": tname, "error": "unable to read"})
    return {"status": "success", "tables": tables, "count": len(tables)}


# ═══════════════════════════════════════════════════════════════════════
# TOOL 6 : Query a feature table
# ═══════════════════════════════════════════════════════════════════════

def query_feature_table(table_name: str, query: str = "") -> dict:
    """Run a SELECT query on a feature table that was previously created.

    Use this to inspect, filter, or aggregate data inside feature tables
    stored in features/<table_name>.db.

    If no query is provided, returns all rows (SELECT * FROM <table_name>).

    Args:
        table_name: Name of the feature table to query.
        query: Optional SQL SELECT query. If empty, defaults to
               SELECT * FROM <table_name>. The query runs against the
               feature database so the only table available is <table_name>.

    Returns:
        A dict with columns, rows (up to 100), and total row count.
    """
    if not _SAFE_NAME_RE.match(table_name):
        return {"status": "error", "error": f"Invalid table name: '{table_name}'"}
    db_path = _features_db_path(table_name)
    if not os.path.exists(db_path):
        return {"status": "error", "error": f"Feature table '{table_name}' does not exist. Use list_feature_tables to see available tables."}
    try:
        conn = sqlite3.connect(db_path)
        conn.row_factory = sqlite3.Row
        sql = query.strip() if query.strip() else f"SELECT * FROM {table_name}"
        cursor = conn.execute(sql)
        columns = [desc[0] for desc in cursor.description] if cursor.description else []
        rows = cursor.fetchall()
        results = [dict(row) for row in rows]
        total = len(results)
        conn.close()
        return {
            "status": "success",
            "table_name": table_name,
            "sql_executed": sql,
            "columns": columns,
            "row_count": total,
            "results": results[:100],
            "truncated": total > 100,
        }
    except Exception as e:
        return {"status": "error", "sql_executed": query, "error": str(e)}


# ═══════════════════════════════════════════════════════════════════════
# TOOL 7 : Export a feature table to CSV
# ═══════════════════════════════════════════════════════════════════════

def export_table_csv(table_name: str) -> dict:
    """Export a feature table to a CSV file and return the download link.

    Args:
        table_name: Name of the feature table to export.

    Returns:
        A dict with the CSV download URL.
    """
    if not _SAFE_NAME_RE.match(table_name):
        return {"status": "error", "error": f"Invalid table name: '{table_name}'"}
    db_path = _features_db_path(table_name)
    if not os.path.exists(db_path):
        return {"status": "error", "error": f"Table '{table_name}' does not exist."}
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.execute(f"SELECT * FROM {table_name}")
        columns = [desc[0] for desc in cursor.description]
        rows = cursor.fetchall()
        conn.close()

        csv_dir = os.path.join(os.path.dirname(__file__), "..", "static", "exports")
        os.makedirs(csv_dir, exist_ok=True)
        csv_path = os.path.join(csv_dir, f"{table_name}.csv")

        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(columns)
            writer.writerows(rows)

        return {
            "status": "success",
            "table_name": table_name,
            "row_count": len(rows),
            "columns": columns,
            "download_url": f"/static/exports/{table_name}.csv",
            "message": f"Export complete: {len(rows)} rows, {len(columns)} columns.",
        }
    except Exception as e:
        return {"status": "error", "error": str(e)}


# ═══════════════════════════════════════════════════════════════════════
# THE NL2SQL AGENT
# ═══════════════════════════════════════════════════════════════════════
# 💡 PEDAGOGICAL POINT:
#    The database schema is injected into the instruction.
#    The LLM uses it to write correct SQL queries.

# This object is used:
#   - standalone (via the selector in the web app)
#   - as a tool for the Sales Analyst (Agent-as-Tool)
nl2sql_agent = Agent(
    name="nl2sql_analyst",
    model="gemini-3.1-flash-lite-preview",
    description="An agent that converts natural language questions into SQL queries and executes them on the database. It can also progressively build feature tables for ML. Use this agent when pre-defined tools cannot answer the question.",
    instruction=f"""You are a SQL expert and data analyst. You translate natural language
questions into SQL queries, execute them, and interpret the results.
You can also build feature tables for machine learning.

## Database schema (SQLite)

```sql
CREATE TABLE products (
    id          INTEGER PRIMARY KEY,
    name        TEXT    NOT NULL,     -- Product name
    category    TEXT    NOT NULL,     -- Audio, Périphérique, Vidéo, Accessoire, Écran, Stockage
    price       REAL    NOT NULL,     -- Selling price (incl. tax)
    cost        REAL    NOT NULL,     -- Supplier cost
    stock       INTEGER NOT NULL,     -- Quantity in stock
    rating      REAL    NOT NULL      -- Customer rating (0 to 5)
);

CREATE TABLE customers (
    id          INTEGER PRIMARY KEY,
    name        TEXT    NOT NULL,     -- Full name
    city        TEXT    NOT NULL,     -- City (Paris, Lyon, Marseille, etc.)
    signup_date TEXT    NOT NULL      -- Signup date YYYY-MM-DD
);

CREATE TABLE orders (
    id           INTEGER PRIMARY KEY,
    product_id   INTEGER NOT NULL,    -- FK to products.id
    quantity     INTEGER NOT NULL,     -- Ordered quantity
    total_price  REAL    NOT NULL,     -- Order total amount
    customer     TEXT    NOT NULL,     -- Customer name (matches customers.name)
    order_date   TEXT    NOT NULL,     -- Date+time as YYYY-MM-DD HH:MM
    status       TEXT    NOT NULL,     -- livrée (delivered), en cours (pending), annulée (cancelled)
    FOREIGN KEY (product_id) REFERENCES products(id)
);
```

## Reference data
{STATS_SUMMARY}
- Today's date: {TODAY}
- Order statuses: livrée (delivered), en cours (pending), annulée (cancelled)
- Cities: Paris, Lyon, Marseille, Toulouse, Bordeaux, Lille, Nantes, etc.
- Margin formula: price - cost
- Margin rate formula: (price - cost) / price * 100
- To join customers and orders: customers.name = orders.customer

## SQLite date functions (IMPORTANT)
- Extract year: strftime('%Y', order_date)
- Extract month: strftime('%m', order_date)
- Extract year-month: strftime('%Y-%m', order_date)
- Today's date in SQL: date('{TODAY}')
- WARNING: Do NOT use date('now') as it may not match the timezone. Use date('{TODAY}') instead.

## Temporal query patterns — USE THESE (no complex subqueries)

Revenue for the last 12 months:
```sql
SELECT strftime('%Y-%m', order_date) AS month,
       ROUND(SUM(total_price), 2) AS revenue,
       COUNT(*) AS order_count
FROM orders
WHERE status != 'annulée'
  AND order_date >= date('{TODAY}', '-12 months')
GROUP BY month
ORDER BY month
```

Last month's revenue:
```sql
SELECT ROUND(SUM(total_price), 2) AS revenue
FROM orders
WHERE status != 'annulée'
  AND strftime('%Y-%m', order_date) = strftime('%Y-%m', date('{TODAY}', '-1 month'))
```

Quarterly evolution:
```sql
SELECT CASE
    WHEN CAST(strftime('%m', order_date) AS INTEGER) BETWEEN 1 AND 3 THEN 'Q1'
    WHEN CAST(strftime('%m', order_date) AS INTEGER) BETWEEN 4 AND 6 THEN 'Q2'
    WHEN CAST(strftime('%m', order_date) AS INTEGER) BETWEEN 7 AND 9 THEN 'Q3'
    ELSE 'Q4'
  END AS quarter,
  strftime('%Y', order_date) AS year,
  ROUND(SUM(total_price), 2) AS revenue
FROM orders WHERE status != 'annulée'
GROUP BY year, quarter ORDER BY year, quarter
```

## ABSOLUTE RULE — NO HALLUCINATION

⚠️ You must NEVER invent, guess or rephrase a product name, customer name,
or number. You must ALWAYS base your answer EXCLUSIVELY on SQL results returned
by the execute_sql tool. Quote names and values EXACTLY as returned.

## Product catalog (EXACT names — never modify them)
{PRODUCTS_LIST}

## Conversation tracking
When the user asks a follow-up question referencing a previous exchange
(pronouns, "and per month?", "how many?", "that one"), use the conversation
history to understand the context and build the correct SQL query.
Always rephrase the complete question in your response before showing the SQL.

## Feature Engineering tools

You have tools to progressively build ML feature tables:

### Typical workflow
1. **list_feature_tables** → see existing tables
2. **create_feature_table** → create an empty table with desired columns
3. **execute_sql** → test the SELECT query on shop.db
4. **insert_query_results** → inject results into the feature table
5. **add_column** → add a new column if needed
6. **query_feature_table** → inspect or verify the feature table contents
7. Repeat 3-6 throughout the conversation to enrich the table
8. **export_table_csv** → export to CSV for download

### Available tools
- **execute_sql(query)** — SELECT query on shop.db (read-only)
- **create_feature_table(table_name, columns)** — creates a feature table
  Example: create_feature_table("monthly_kpi", "month TEXT PRIMARY KEY, revenue REAL, order_count INTEGER")
- **add_column(table_name, column_name, column_type)** — adds a column
  Example: add_column("monthly_kpi", "avg_basket", "REAL")
- **insert_query_results(table_name, source_query)** — runs SELECT on shop.db and inserts into the table
  ⚠️ SELECT columns must match the target table columns
  Uses INSERT OR REPLACE: duplicates are overwritten if the table has a PRIMARY KEY
- **list_feature_tables()** — lists existing feature tables
- **query_feature_table(table_name, query)** — runs a SELECT query on a feature table
  Example: query_feature_table("monthly_kpi", "SELECT * FROM monthly_kpi WHERE revenue > 10000")
  If query is omitted, returns all rows (SELECT *)
- **export_table_csv(table_name)** — exports to CSV, returns the download link

### Feature engineering tips
- Use a PRIMARY KEY (month, customer, product…) to avoid duplicates
- Name columns explicitly (monthly_revenue, cancellation_rate, recency_days)
- When the user says "add that to the table", use add_column then insert_query_results
- Always offer to export to CSV when the table is ready

## Your rules
- ALWAYS respond in English
- For SELECT on shop.db: use ONLY execute_sql (read-only)
- For feature building: use create_feature_table, add_column, insert_query_results
- ALWAYS call a tool before answering — NEVER guess a result
- ALWAYS show the SQL query you generated before the results
- Quote product names and numbers EXACTLY as returned by SQL
- Present the SQL query in a code block
- Present results as a structured table
- Add an interpretation of the results
- If the question is ambiguous, suggest multiple interpretations
- Use readable English aliases in your queries (AS column_name)
- When creating or modifying a feature table, show the table structure
- When exporting to CSV, display the download link

## Response format
1. COMPLETE rephrasing of the question (with context if it's a follow-up)
2. Generated SQL query
3. Results as a table (with EXACT returned values)
4. Interpretation

Always suggest a follow-up question.
""",
    tools=[execute_sql, create_feature_table, add_column, insert_query_results,
           list_feature_tables, query_feature_table, export_table_csv],
)

# Alias for compatibility with `adk run` and `adk web` (which look for root_agent)
root_agent = nl2sql_agent
